### PR TITLE
Sheffler/merge220513

### PR DESCRIPTION
**Pull request by willsheffler**
Updates file formats in rpxdock from pickle files to tarballs containing portable representations. The main reason for this is portability -- rpxdock should no longer be dependent on specific versions of libraries like numpy. Should also play nice with newer version of python. Also plays nice with pymol, if installed with conda -c schrodinger pymol-bundle. There are some really nice visualization utilities now included, like showing xforms, points, vectors etc and body objects.

Some of the utilitarian code (aka, the code I have duplicated in 5 projects lol) has been taken out into a library creatively called willutil. Thus, willutil is now a dependency of rpxdock. Hopefully it won't be too much of a problem... the following command should install it
pip install git+https://github.com/willsheffler/willutil.git
and this command most of the tests
python -m pytest --pyargs willutil 

once this pull request comes to fruition, it should be possible to pip install rpxdock like this:
pip install git+https://github.com/willsheffler/rpxdock.git
either before or after, pyrosetta must be installed. however we do it, installing pyrosetta will be a manual step... we can't include the user/pass for the conda channel. 
with pyrosetta installed, you will be able to run the tests with
python -m pytest --pyargs willutil 

new file format stuff:

Older pickle files can be converted by running:
<python> rpxdock/app/util/convert_rpxdata_to_portable_format.py <.pickle files>

internally in the code, these functions can be used:

      rp.motif.convert_respairdat_to_netcdf(dat, newfname)
      rp.motif.respairscore_to_tarball(dat, newfname)
      rp.motif.xmap_to_tarball(dat, newfname)
      rp.search.result_from_tarball(fname)
      rp.search.result_to_tarball(dat, newfname)

the new result files contain pdb representations of the result.bodies field of the result object. these pdbs get read and put back into result.bodies when read in with result_from_tarball, so it should behave the same as the old pickle files, other than a different function call to read in the files.

This pr also includes lots of bug fixes and other new stuff like the asymmetric cage modeling. It probably also includes some new bugs too.

### CODE REVIEW

**Comment by yhsia** [comment]
@willsheffler I pulled your branch and I tested it on the digs.

1. I installed `willutil.git` successfully with no issues.
2. `python -m pytest --pyargs willutil` runs with 86 `passed` with 1 `xfailed`.
3. `rpxdock/app/dock.py --help` runs with no issues.
4. standard `pytest` however is erroring out with `FAILED  - ModuleNotFoundError: No module named 'rmsd'`

**Comment by yhsia** [comment]
issues:
1. loading compressed hscore files seem to take a long time (much longer than before)
2. dumping pdb files from tarball

@willsheffler 
example:
`/home/yhsia/cage_design_2/2022-04-20_twistless_lock_v4/1comp/dock/processing/dump_pdb_from_tarball.py`

usage:
`./dump_pdb_from_tarball.py -av -o dump -i /home/yhsia/cage_design_2/2022-04-20_twistless_lock_v4/1comp/dock/output/I3/twstlssbb-026_3_asu_alignZX_-0/I3.result.txz`

current error:
`Traceback (most recent call last):
  File "./dump_pdb_from_tarball.py", line 101, in <module>
    rpx_pickle.dump_pdbs(best[0:nout_top], lbl=direction, output_prefix=f"{args.outpath}/{sym}_", use_orig_coords=True, output_asym_only=args.asu, output_closest_subunits=args.closest)
  File "/home/yhsia/git/rpxdock/rpxdock/search/result.py", line 220, in dump_pdbs
    self.dump_pdb(imodel, output_prefix=prefix_tmp, **kw)
  File "/home/yhsia/git/rpxdock/rpxdock/search/result.py", line 265, in dump_pdb
    body_names = [b.label for b in bod]
  File "/home/yhsia/git/rpxdock/rpxdock/search/result.py", line 265, in <listcomp>
    body_names = [b.label for b in bod]
AttributeError: 'list' object has no attribute 'label'
`

**Comment by willsheffler** [comment]
Yang, try the results stuff again. I'm looking into why the loading takes so long now... it's weird.

**Comment by willsheffler** [comment]
it should be ok to use pickles for the xmap files I think... that's all internal stuff that won't change. Try giving something like this for hscore files, and let me know how that goes on your end

<path>/pdb_res_pair_data_si30_rots_H_ILV_SSindep_p0.5_b1_base.rpx.txz
<path>/pdb_res_pair_data_si30_rots_H_ILV_SSindep_p0.5_b1_hier0_Kflat_2_1.pickle
<path>/pdb_res_pair_data_si30_rots_H_ILV_SSindep_p0.5_b1_hier1_Kflat_1_1.pickle
<path>/pdb_res_pair_data_si30_rots_H_ILV_SSindep_p0.5_b1_hier2_Kflat_1_1.pickle
<path>/pdb_res_pair_data_si30_rots_H_ILV_SSindep_p0.5_b1_hier3_Kflat_1_0.pickle
<path>/pdb_res_pair_data_si30_rots_H_ILV_SSindep_p0.5_b1_hier4_Kflat_1_0.pickle

**Comment by yhsia** [comment]
@willsheffler 

Looks like it dumps pdb files now -- but the filenames are filled with `tmp` instead of the name of the components.

example:
old: `I3__top0_00__twstlssbb-026_3_asu_alignZX_-0_+0_F.pdb`
new: `I3__top0_00__tmp.pdb`

**Comment by yhsia** [comment]
> it should be ok to use pickles for the xmap files I think... that's all internal stuff that won't change. Try giving something like this for hscore files, and let me know how that goes on your end
> 
> /pdb_res_pair_data_si30_rots_H_ILV_SSindep_p0.5_b1_base.rpx.txz /pdb_res_pair_data_si30_rots_H_ILV_SSindep_p0.5_b1_hier0_Kflat_2_1.pickle /pdb_res_pair_data_si30_rots_H_ILV_SSindep_p0.5_b1_hier1_Kflat_1_1.pickle /pdb_res_pair_data_si30_rots_H_ILV_SSindep_p0.5_b1_hier2_Kflat_1_1.pickle /pdb_res_pair_data_si30_rots_H_ILV_SSindep_p0.5_b1_hier3_Kflat_1_0.pickle /pdb_res_pair_data_si30_rots_H_ILV_SSindep_p0.5_b1_hier4_Kflat_1_0.pickle

If both of the *.pickle and the *.xmap.txz versions are there, which one gets prioritized?

I'll have to delete one set to test it right?

**Comment by willsheffler** [comment]
prefer .pickle format for motif files for speed
fix result .tgz output
output pickle and txz result by default
added the following related options:

--save_results_as_tarball
     default true
     save results as portable xz compressed tarball

--save_results_as_pickle 
     default true
     save results as fast loading python pickle

--overwrite_existing_results 
     default false
     overwrites existing results

**Comment by willsheffler** [comment]
merged changes from master. had to fix some tests, mostly the onecomp stuff and helix_tricks.  generated portable versions of these test data files:

rpxdock/data/testdata/test_cage_term_access.result.txz
rpxdock/data/testdata/test_axel.result.txz
rpxdock/data/testdata/test_cage_termini_dirs.result.txz
rpxdock/data/testdata/test_cage_onecomp_grid_termini_dirs.result.txz
rpxdock/data/testdata/test_cage_onecomp_grid_term_access.result.txz
rpxdock/data/testdata/test_cage_onecomp_hier_term_access.result.txz
(maybe a few others)

**Comment by yhsia** [comment]
@willsheffler looks like `test_asym` is failing.

**Comment by yhsia** [comment]
@willsheffler some misc. issues I'm running into testing the new results code:

1. the *.txz version of the results file doesn't seem to have a `sym` object (the *.pickle version does).
2. the *.txz file name is not consistent with the *.pickle version (XX_Result.pickle vs XX.result.txz).
3. something with `bodlab` being out of range when accessing both the *.pickle and *.txz files even though there are clearly more `model`s. Still looking into this.

**Comment by yhsia** [comment]
@willsheffler looks like most stuff is fixed.

**important stuff:**

- [ ] 1. Need to generate generic *.txz hscore files

- [ ] 2. During the run the pre-run verbose is no longer showing (eg. the command line, arguments passed, etc.)

**not important stuff:**
- [ ] 3. dumping *.pdb files from *.txz result objects, the `sym` field has single quotes compared to the *.pickle version which doesn't. `'O43'_rest_of_the_filename.pdb` vs `O43_rest_of_the_filename.pdb`

- [ ] 4. when the filters remove all viable docks, currently rpxdock prints a line and errors out eventually because the `scores` field is empty. I think we decided to dump an empty result file for consistency, but I think maybe we should end the run with a "run successfully finished" message rather than a error.

**need to fix/do for the future:**
- [ ] 5. fix broken --score_self
- [ ] 6. implement multi-interface allowed-resis
- [ ] 7. trim_resis/helix maybe broken?

**Pull request merged**
